/**
 * 业务错误码枚举。
 * 对外契约应保持稳定，前端/调用方按 code 做分支，而不是依赖 HTTP 文案。
 */
export enum ErrorCode {
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  AUTH_TOKEN_MISSING = "AUTH_TOKEN_MISSING",
  AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  /** refresh token 重放：已吊销 token 再次使用 */
  AUTH_TOKEN_REUSED = "AUTH_TOKEN_REUSED",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",
  /** 登录失败次数过多触发 Redis 限流 */
  AUTH_RATE_LIMITED = "AUTH_RATE_LIMITED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  LOCK_NOT_ACQUIRED = "LOCK_NOT_ACQUIRED",
  IDEMPOTENCY_IN_PROGRESS = "IDEMPOTENCY_IN_PROGRESS"
}
