apiVersion: v1
kind: Secret
metadata:
  name: enterprise-node-backend-secret
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/enterprise_backend?schema=public
  JWT_ACCESS_SECRET: replace-me
  JWT_REFRESH_SECRET: replace-me

